### PR TITLE
V0.11.1

### PR DESCRIPTION
**Pull request by chrsdietz**
Patch version with small fixes for version 0.11.0 of dashboard.

Changes in this pull request include:
- Source changes "created date" in to a string
- User is sent to the Source recap page instead of the logs page.
- Bar chart is reformatted for exceptionally long names
- Empty message is displayed again on logs list.

@ mention the name of person who needs to review

### CODE REVIEW

**Comment by chrsdietz** [comment]
This should be tagged as a patch for version 0.11.0.  Most of the bugs fixed are already in master.

**Comment by michaelmyers** [comment]
@chrsdietz what should we do with this branch?  Can we merge it?

**Comment by chrsdietz** [comment]
I don't think it can be directly merged right now.  I need to cherry-pick the patches and then delete the branch.

**Comment by chrsdietz** [comment]
#271 is the answer

**Pull request closed without merging**
